### ISSUE TITLE
More information on when interaction with external service fails + offline mode?

### ISSUE THREAD

**Issue by yarikoptic** [con/tributors#29]
```
$> vim .tributors  # provided a full name for a person
```

and expected `update` to just update "name", but it seems did go for a full "interaction":

```
$> tributors update zenodo
INFO:zenodo:Updating .zenodo.json
Response 403: rate limit exceeded, cannot retrieve contributors.
```

1. would be nice to report which service failed... if we even "hard code" some information about most common gotchas and inform user here ("rate limit on communication with X exceeded.  There should be only up to Y interactions.  To increase the limit you need to obtain an API key Z from A, or just wait B and rerun again.
2. `update` should get an option to perform only `offline` updates (like here)

**Comment by vsoch** [comment]
That is always the GitHub API, and there is a note about it in the docs but we could add a note that it's the GitHub api in the error message.

**Comment by yarikoptic** [comment]
Good docs are great, but IMHO informative --help and error messages are a better guidance. Take git as an example (although indeed it's man pages are now not that easy to digest due to age/richness of functionality - it is then when additional distilled docs/blogs/demos come handy).

**Comment by vsoch** [comment]
Two fixes here:

 - the error message is updated to alert about the GitHub API.
 - Zenodo does not require a doi for generation, it just won't add as much metadata
 - there can't really be support for offline because we always use the GitHub contributors as a source of truth, and that requires the API. If we fallback to the .tributors file then that would mean cross-pollination between contributor files, which we don't necessarily want.

The feature you will want for this "offline" mode is to update explicitly from one to another, and `.tributors` can be a source for the update. Closing here in favor of this issue #32
